### ISSUE TITLE
This script is not activated in the newly opened chatgpt tab

### ISSUE THREAD

**Issue by JJQuiet** [adamlui/chatgpt-widescreen#10]
When I refresh the page again, it starts to work

**Comment by adamlui** [comment]
@JJQuiet thanks for reporting, are you using the userscript or browser extension?

**Comment by adamlui** [comment]
@JJQuiet also what browser and userscript manager if applicable are you using?

**Comment by JJQuiet** [comment]
I am using the widescreen script from the Google Chrome Tampermonkey plugin

**Comment by adamlui** [comment]
@JJQuiet sorry I couldn't replicate the issue in Chrome Tamperemonkey, in TM > Dashboard, is version v4.18.1? Also is ChatGPT Widescreen v2023.5.22? If so, can you press Ctrl+Shift+I when it doesn't load > Console and do you see any errors? Also are you running any other scripts or extensions?

**Comment by JJQuiet** [comment]
All the extensionsI run are displayed on the toolbar，and there are no other scripts，while I enter chat.openai.com in the NEW Tab,it shows below:
![image](https://github.com/adamlui/chatgpt-widescreen/assets/60891137/83c0b409-b2ab-4026-9de9-7400bf3fbb45)
While I refresh again, it shows below:
![image](https://github.com/adamlui/chatgpt-widescreen/assets/60891137/87b57f3a-5e4b-4913-9f9c-9642d77f06a0)

**Comment by adamlui** [comment]
@JJQuiet thanks for the useful screenshot, can you find line 57:

```js
// @noframes
```

And insert a new line after that:
```js
// @run-at              document-idle
```

Save and tell me if it works?

**Comment by JJQuiet** [comment]
I'm sorry to inform you that it's still useless

**Comment by adamlui** [comment]
I don't know why your Tampermonkey doesn't load it unless refreshed. Console shows no errors coming from my script, only errors for extensions you are running. Can you install the extension instead and see if it works: https://chrome.google.com/webstore/detail/chatgpt-widescreen-mode/jgnjpnmofkalfliddjelaciggjgnphgm

**Comment by JJQuiet** [comment]
It works！ Thank you very much!

**Comment by adamlui** [comment]
@JJQuiet if you want, you couuld help out by leaving a positive review on Chrome store

**Comment by JJQuiet** [comment]
I am pleasure to give a positive review
