### ISSUE TITLE
Buttons invisible in light mode

### ISSUE THREAD

**Issue by RdJNL** [adamlui/chatgpt-widescreen#11]
I'm using ChatGPT in light mode and the Chrome extension and the buttons aren't visible. They're there, if I hover over them, I get a tooltip and clicking works too, but since the prompt is white and the buttons are white too, they're invisible.

**Comment by adamlui** [comment]
Hey @RdJNL OpenAI had updated their UI so my scheme detection logic broke, but I will be uploading an updated version today (that Google should approve by tomorrow)

**Comment by adamlui** [comment]
@RdJNL Google approved the update, it works in light mode now:

![image](https://github.com/adamlui/chatgpt-widescreen/assets/10906554/27d89b79-dbc7-49d5-b4dc-1374e91fae46)

Also I added a fullscreen mode! You can update @ https://chatgptevo.com/widescreen/chrome

**Comment by RdJNL** [comment]
Thanks, it's working.
