### ISSUE TITLE
Safari Upload Button Bug

### ISSUE THREAD

**Issue by Aubermean** [adamlui/chatgpt-widescreen#19]
Hi, I have problems with Safari using either Stay or Tampermonkey.

<img width="1046" alt="Screenshot 2023-09-23 at 4 11 04 PM" src="https://github.com/adamlui/chatgpt-widescreen/assets/58298118/4b432409-45d7-492c-9657-5d08562d4699">

First load, no problem.

<img width="1042" alt="Screenshot 2023-09-23 at 4 11 54 PM" src="https://github.com/adamlui/chatgpt-widescreen/assets/58298118/bf35f446-b0d1-4dfb-8697-e375a533a485">

But after changing pages and going back, sporadically, this grey + button appears. A way to reproduce is by clicking the New + button straight away. If you refresh, it's gone.

Another issue in Safari is the alignment is a little bit off center, but I don't know this is Safari specific:

<img width="1223" alt="Screenshot 2023-09-23 at 4 14 17 PM" src="https://github.com/adamlui/chatgpt-widescreen/assets/58298118/e07af897-2254-404c-b798-f5d330aa1acb">

I can confirm that all your other extensions work in Safari completely fine!

PS. I think you should add a refined version of this [Auto-send next response script](https://greasyfork.org/en/scripts/472713-chatgpt-auto-prompt-sender) to your portfolio of efficient ChatGPT Userscripts! Right now, the design is clunky because you have to navigate to the menu. It would be cool if it used ChatGPT.js! One idea I had, is that you could make a rule that if the response has one or two extra returns at the end, it's auto-sent. Because if you press enter while it's still responding, it adds a return to the textfield. You couldn't auto-send if the text field contained simply any text, because it would auto send while you were still typing. Maybe you could go based on focus or some other advanced techniques. I had a try myself to put it together, but I am no JS expert :)

**Comment by adamlui** [comment]
Hey thanks for the feedback @Aubermean, I don't have a Mac so can't test it, but what does clicking the long grey bar do?

**Comment by Aubermean** [comment]
It offers to upload a file. It looks like the + circle that's usually on the left side of the textfield is bumped below.

If you want me to give you specific information that can help you pinpoint the issue let me know.

<img width="1202" alt="Screenshot 2023-09-23 at 4 42 35 PM" src="https://github.com/adamlui/chatgpt-widescreen/assets/58298118/bca64c3d-c958-4b7c-a353-ece9db83ec56">
<img width="1202" alt="Screenshot 2023-09-23 at 4 41 26 PM" src="https://github.com/adamlui/chatgpt-widescreen/assets/58298118/faab2f82-bd2a-4494-9743-587938964137">

**Comment by adamlui** [comment]
When it's like that, if you could right-click on the <form> that contains the chatbar and copy the Outer HTML

**Comment by adamlui** [comment]
@Aubermean the off-center alignment is fixed in 2023.9.24.1! https://chatgptwidescreen.com/greasyfork

**Comment by adamlui** [comment]
Hey @Aubermean I finally subscribed to Plus and fixed the image upload bug! You can update in the menu 'About ChatGPT Widescreen > Check for Updates'
