### ISSUE TITLE
Text field issue (Safari only?)

### ISSUE THREAD

**Issue by Aubermean** [adamlui/chatgpt-widescreen#20]
Depending on the size of the browser window, the text field resizes. However it could use use adjustment, as my average browser window size on a 13inch screen could benefit from a wider text field. You can see that when I make the window smaller, it widens and fits the page.

<img width="1053" alt="Screenshot 2023-09-23 at 4 22 06 PM" src="https://github.com/adamlui/chatgpt-widescreen/assets/58298118/66b9f72e-65f9-47b1-9f24-b6c500ba0297">
<img width="1021" alt="Screenshot 2023-09-23 at 4 22 20 PM" src="https://github.com/adamlui/chatgpt-widescreen/assets/58298118/f7a2302e-dbb0-4448-8a8d-2ff8ffd24608">

**Comment by adamlui** [comment]
Hey @Aubermean does the text bar do the auto-expand even with the userscript off?

**Comment by Aubermean** [comment]
https://github.com/adamlui/chatgpt-widescreen/assets/58298118/0afa9a3c-18e2-45de-8cc8-cb5059d59580

Made a short clip to show, might give you a lightbulb moment figuring out why the CSS is off center when in widescreen mode!

> Hey @Aubermean does the text bar do the auto-expand even with the userscript off?

I just tested it, and yes it behaves the same with the userscript off. I would have thought that having widescreen mode enabled would mean the textfield would be wide screen (no whitespace) but only the stuff above changes:


https://github.com/adamlui/chatgpt-widescreen/assets/58298118/7a56bb2a-f66f-4ca5-8a36-d7877dd1d66f

**Comment by adamlui** [comment]
@Aubermean can you update to 2023.9.23 @ https://chatgptwidescreen.com/greasyfork and check out if the fully expanded chatbar works?

**Comment by Aubermean** [comment]
> @Aubermean can you update to 2023.9.23 @ https://chatgptwidescreen.com/greasyfork and check out if the fully expanded chatbar works?

Awesome, it works!

<img width="1202" alt="image" src="https://github.com/adamlui/chatgpt-widescreen/assets/58298118/2f6c67fb-7926-4f16-a094-8073c2d2a607">

**Comment by adamlui** [comment]
@Aubermean I closed this as completed even though you provided the helpful off-center CSS video so the list of issues is more organized, also I will investigate it later tonight as I've been up for many hours and need to sleep now
