### ISSUE TITLE
Remove footer div "ChatGPT may produce inaccurate...."

### ISSUE THREAD

**Issue by Aubermean** [adamlui/chatgpt-widescreen#21]
The div at the bottom of the page takes up a lot of space on a smaller (non-mobile) screen. It would be really smart if you could add a menu option to hide this div if people want to.

The classic footer:

<img width="1047" alt="Screenshot 2023-09-23 at 4 28 27 PM" src="https://github.com/adamlui/chatgpt-widescreen/assets/58298118/13c683de-3d0e-4182-a982-ca5f125e147c">

Without the disclaimer div:

<img width="1030" alt="Screenshot 2023-09-23 at 4 27 05 PM" src="https://github.com/adamlui/chatgpt-widescreen/assets/58298118/0e9d1826-9d6d-4fb6-bc88-79ff7f28f5af">

and when you remove the help div too, it's even better:

<img width="1036" alt="Screenshot 2023-09-23 at 4 27 43 PM" src="https://github.com/adamlui/chatgpt-widescreen/assets/58298118/a91eb0de-161c-447f-813e-8391711c16e0">

**Comment by adamlui** [comment]
@Aubermean ok, do you want to start off being a contributor by inserting the CSS, then I add it to menu?

If so, Ctrl + F for this function:

```js
    function updateTweaksStyle() {
        tweaksStyle.innerText = (
              site == 'openai' ? inputSelector + ' { padding-right: 148px } '  // narrow input to accomdate buttons
                               + 'div.group > div > div > div > div:nth-child(2) { ' // move response paginator
                                   + 'position: relative ; left: 66px ; top: 7px } ' : '' ) // ...below avatar to avoid cropping
        + ( !config.tcbDisabled ? tcbStyle : '' ) // expand text input vertically
    }
```

Next, make it like this instead:

```js
    function updateTweaksStyle() {
        tweaksStyle.innerText = (
            site == 'openai' ? (
                ( inputSelector + ' { padding-right: 148px } ' // narrow input to accomdate buttons
                + 'div.group > div > div > div > div:nth-child(2) { ' // move response paginator
                    + 'position: relative ; left: 66px ; top: 7px } ' // ...below avatar to avoid cropping
                + 'selector { property: value }' // hide footer text
                + 'selector { property: value }' ) // hide help button text
            : ''
        + ( !config.tcbDisabled ? tcbStyle : '' ) // expand text input vertically
    }
```

Then, replace the `selector { property: value }` w/ the CSS you used

**Comment by adamlui** [comment]
And also update the version number to 2023.9.23.1. And to commit it:

- Click pencil icon on https://github.com/adamlui/chatgpt-widescreen/blob/main/greasemonkey/chatgpt-widescreen-mode.user.js
- Follow the on-screen instructions to fork your own repo
- Paste your changes, then save and leave the edit note "Added CSS styles to hide footer text/button"
- Somewhere on your forked repo you should see a "Merge changes" and it will walk you thru creating a pull request

**Comment by adamlui** [comment]
@Aubermean I have to sleep now but you get a badge called "Pull Shark" after creating 2 or 3 Pull Requests

**Comment by adamlui** [comment]
@Aubermean I added it in v2023.9.24.4! It is off by default:

![image](https://github.com/adamlui/chatgpt-widescreen/assets/10906554/78eaa9dd-d04b-43e9-a963-148de0d480f5)

https://chatgptwidescreen.com/greasyfork
