### ISSUE TITLE
TWO COLUMN WIDTH TWO COLUMN CONTENT 

### ISSUE THREAD

**Issue by lozn00** [adamlui/chatgpt-widescreen#25]
![image](https://github.com/adamlui/chatgpt-widescreen/assets/14260426/a6a3b4ad-ed70-4e04-a662-efa668e25507)
![B2YRAI$7JQF%K8FD3M(H9MY](https://github.com/adamlui/chatgpt-widescreen/assets/14260426/0f8f9a03-6bab-4077-9b05-49e68a4eb9f0)

**Comment by adamlui** [comment]
Hey @lozn00 sorry I don't read/write Chinese, can you explain the problem and what your environment is

**Comment by adamlui** [comment]
@lozn00 also can you tell me what other extensions or scripts you have enabled
