### ISSUE TITLE
Since the UI was updated with chatGpt turbo, I've been experiencing errors in the UI. 

### ISSUE THREAD

**Issue by comonetso** [adamlui/chatgpt-widescreen#28]
As you can see in the screenshot, the icons next to the send button are messed up, and the ? button (help light) in the bottom right corner is missing.  

![Screenshot 2023-11-11 at 00 01 00](https://github.com/adamlui/chatgpt-widescreen/assets/76943037/e34bb557-8d50-42e6-bcb2-8935165e3b28)

**Comment by adamlui** [comment]
Thanks for the info @comonetso, I've been updating all my ChatGPT apps to work with new UI, currently am working on ChatGPT Infinity, then I will fix Widescreen next

**Comment by comonetso** [comment]
Thank you for your quick response. 
I have always appreciated using
I hope it will be updated soon.

**Comment by adamlui** [comment]
Hey @comonetso I've been coding all night so I have to sleep but I promise I will fix it firsts thing when I wake up and after i eat

**Comment by adamlui** [comment]
@comonetso I fixed it, if you are using the script you can update immediately @ https://script.chatgptwidescreen.com, if you are using the extension it will automatically update probably tomorrow after they review the changes

**Comment by adamlui** [comment]
@comonetso also can you tell me what your browser is and if you are using the extension or the userscript, in case I need to do more fixing?

**Comment by comonetso** [comment]
My main browser is Whale browser, and last I checked, Edge and Chrome are also experiencing the same symptoms.  

Thank you for all the hard work you are doing to fix this.

**Comment by adamlui** [comment]
@comonetso it's still happening with the userscript? (the Chrome/Edge extension updates weren't approved yet)

**Comment by comonetso** [comment]
It looks like the Chrome Web Store hasn't been updated yet,  
I'll update the post-test comment when it does.

**Comment by comonetso** [comment]
I'm not seeing any updates on the Crop Webstore yet

When will the update be approved? The clunky UI is starting to get quite frustrating,

 and I appreciate the hard work you've put into it.

**Comment by comonetso** [comment]
Thank you.

However, when I tested it, there is a bug that when I turn off the Wide Screen On screen, the chat input window appears to be applied, but actually remains unturned, and Toastmsg is also displayed as On.

This doesn't bother me in practice, as I always use Wide Screen On.

I leave a message for you to note

Thank you for your quick response.

**Comment by adamlui** [comment]
@comonetso you mean it always stays Wide Screen mode no matter what? also what is your browser

**Comment by comonetso** [comment]
I'm using a western browser, and it's the same on both Chrome and Edge.

It stays on even when I turn it off, so the conclusion is that it always stays in screen mode,,,

**Comment by adamlui** [comment]
@comonetso that is quite strange, can you try removing and re-installing the extension?

**Comment by comonetso** [comment]
I uninstalled and reinstalled and it works fine. 



Thanks.

**Comment by comonetso** [comment]
I'm glad to see that the chat input window has been widened with this fix.

**Comment by adamlui** [comment]
Glad it works! If you want to support it, you could leave a review on the Chrome store or
https://www.producthunt.com/products/chatgpt-widescreen-mode/reviews/new or
https://www.futurepedia.io/tool/chatgpt-widescreen-mode#chatgpt-widescreen-mode-review
