### ISSUE TITLE
Wide screen mode cut off the indicator to switch between ChatGPT replies

### ISSUE THREAD

**Issue by nhan000** [adamlui/chatgpt-widescreen#3]
To reproduce:

- Open a new tab with ChatGPT, choose Wide Screen mode
- Enter a prompt, then click "Regenerate Response"
- Drag 1 the right or the left side of the browser window to resize it and see the bug.

It's supposed to look like this

![image](https://user-images.githubusercontent.com/85216095/231290032-b48991f2-acc3-413a-b2cb-5dc797bce01f.png)

Instead, you can have the indicator partially covered

![image](https://user-images.githubusercontent.com/85216095/231289047-f409d5d8-0b1f-4b2c-9ff6-71e98042c92b.png)

Or almost completely covered

![image](https://user-images.githubusercontent.com/85216095/231289960-2702dbf9-3cb7-4569-a38a-acb9a9c502d0.png)

**Comment by adamlui** [comment]
@nhan000 thanks for reporting the glitch! Are you using the Chrome extension or the Greasemonkey userscript (also which manager if so)?

**Comment by nhan000** [comment]
Hi @adamlui I was using the Greasemonkey userscript with Tampermonkey on Edge Stable (all updated).

I didn't know there was a Chrome extension so thanks for mentioning it. However, I just tried it and it has the same issue.

I forgot one more detail in the bug report: It happens with the Full-window mode as well.

**Comment by adamlui** [comment]
@nhan000 I fixed it by moving paginator below avatar:

![image](https://user-images.githubusercontent.com/10906554/231315580-243c6581-8e70-401a-a7fb-74d64c7da2c6.png)

On GF update is ready already, on Chrome Store new version will take up to days to approve

**Comment by adamlui** [comment]
@nhan000 I renamed the repo dir so auto-sync got messed up, now GF serves updated code so you can update now!
