### ISSUE TITLE
不能複製與右鍵

### ISSUE THREAD

**Issue by KamiyaMinoru** [adamlui/chatgpt-widescreen#31]
使用此腳本會沒辦法複製內文或者對內文按右鍵

**Comment by adamlui** [comment]
@KamiyaMinoru 嘿，这个问题发生在什么用户脚本管理器和浏览器版本中？

**Comment by KamiyaMinoru** [comment]
Edge109.0.1518.140 . Windows 7, 竄改猴

**Comment by adamlui** [comment]
@KamiyaMinoru 您使用的是 Microsoft Edge 插件或用户脚本吗？ 另外，用户脚本管理器的名称是什么？

**Comment by KamiyaMinoru** [comment]
腳本, 用竄改猴(tampermonkey)掛腳本的

Adam Lui 刘展鹏 ***@***.***> 於 2023年11月29日 週三 下午8:25寫道：

**Comment by adamlui** [comment]
@KamiyaMinoru 在最新的 Edge 中，复制按钮和右键菜单的复制功能都适用于我：

![image](https://github.com/adamlui/chatgpt-widescreen/assets/10906554/3ce4d7e2-00d3-48c0-af17-71375c6bd636)

您还运行哪些其他脚本？ 也许其中之一导致了问题。 您还可以尝试在 edge://settings/help 中更新 Edge

**Comment by KamiyaMinoru** [comment]
1. 這是Windows7最新也是最後的版本的Edge了
2. 只有在開啟(包括單獨開啟)這個腳本的時候會出現這問題, 關閉就好了

**Comment by adamlui** [comment]
@KamiyaMinoru 抱歉，我没有 Windows 7，所以不知道如何修复它，您还应该尝试禁用隐藏页脚模式（其中有一个 CSS 样式禁用用户选择）

**Comment by KamiyaMinoru** [comment]
Hi Adam, 你是個精準的天才! 關掉這個功能以後看起來一切都變得正常了

Adam Lui 刘展鹏 ***@***.***> 於 2023年11月29日 週三 下午8:55寫道：
