### ISSUE TITLE
能不能不隐藏使用次数达到上限的提醒

### ISSUE THREAD

**Issue by visayafan** [adamlui/chatgpt-widescreen#34]
ChatGPT始终不回答，查找了半天原因才发现是回答次数超过上限了，开启chatgpt-widescreen后把下面的消息隐藏了。

![image](https://github.com/adamlui/chatgpt-widescreen/assets/1766538/21b817c9-2d5b-4882-aaad-d52499650f08)

**Comment by adamlui** [comment]
嘿@visayafan我不再订阅Pro了，所以我无法让该消息出现，但下次出现时，您可以右键单击错误>检查元素>右键单击突出显示的HTML>复制外部HTML>粘贴 在这里？ 另外，如果您禁用“隐藏页脚”和“隐藏页眉”，它现在可能会再次显示

**Comment by visayafan** [comment]
> 嘿@visayafan我不再订阅Pro了，所以我无法让该消息出现，但下次出现时，您可以右键单击错误>检查元素>右键单击突出显示的HTML>复制外部HTML>粘贴 在这里？ 另外，如果您禁用“隐藏页脚”和“隐藏页眉”，它现在可能会再次显示

今天又出现了。禁用“隐藏页脚”和“隐藏页眉”无效，看来和这两个设置无关。

![image](https://github.com/adamlui/chatgpt-widescreen/assets/1766538/8725c1a3-7e29-4e7f-956c-a5eec211eee2)

`<div class="relative flex w-full flex-col lg:w-[calc(100%-115px)] agent-turn"><div class="font-semibold select-none">ChatGPT</div><div class="flex-col gap-1 md:gap-3"><div class="flex flex-grow flex-col max-w-full"><div data-message-author-role="assistant" data-message-id="aaa2b32a-c2e2-47c3-8a8a-b478d4637e1f" class="min-h-[20px] text-message flex flex-col items-start gap-3 whitespace-pre-wrap break-words [.text-message+&amp;]:mt-5 text-red-500"><div class=""></div><div class="mb-2 py-2 px-3 border text-gray-600 rounded-md text-sm dark:text-gray-100 border-red-500 bg-red-500/10"><div class="flex items-center gap-6"><span>You've reached the current usage cap for GPT-4. You can continue with the default model now, or try again after 1:18 AM. <a href="https://share.hsforms.com/16d0ZZVM3QZirXnCD_q7u1Q4sk30" target="_blank" rel="noreferrer" class="underline">Learn more</a></span><button class="btn relative btn-light flex-shrink-0 bg-white"><div class="flex w-full gap-2 items-center justify-center">Use default model</div></button></div></div></div></div><div class="mt-1 flex justify-start gap-3 empty:hidden"><div class="text-gray-400 flex self-end lg:self-center justify-center lg:justify-start mt-0 gap-1 visible"><button class="flex items-center gap-1.5 rounded-md p-1 pl-0 text-xs hover:text-gray-950 dark:text-gray-400 dark:hover:text-gray-200 disabled:dark:hover:text-gray-400 md:invisible md:group-hover:visible md:group-[.final-completion]:visible"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="icon-md"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 4C10.8954 4 10 4.89543 10 6H14C14 4.89543 13.1046 4 12 4ZM8.53513 4C9.22675 2.8044 10.5194 2 12 2C13.4806 2 14.7733 2.8044 15.4649 4H17C18.6569 4 20 5.34315 20 7V19C20 20.6569 18.6569 22 17 22H7C5.34315 22 4 20.6569 4 19V7C4 5.34315 5.34315 4 7 4H8.53513ZM8 6H7C6.44772 6 6 6.44772 6 7V19C6 19.5523 6.44772 20 7 20H17C17.5523 20 18 19.5523 18 19V7C18 6.44772 17.5523 6 17 6H16C16 7.10457 15.1046 8 14 8H10C8.89543 8 8 7.10457 8 6Z" fill="currentColor"></path></svg></button><div class="flex gap-1"></div><button class="p-1 pl-0 rounded-md disabled:dark:hover:text-gray-400 dark:hover:text-gray-200 dark:text-gray-400 text-gray-400 hover:text-gray-950 md:invisible md:group-hover:visible md:group-[.final-completion]:visible"><div class="flex items-center gap-1.5 text-xs"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="icon-md"><path fill-rule="evenodd" clip-rule="evenodd" d="M4.5 2.5C5.05228 2.5 5.5 2.94772 5.5 3.5V5.07196C7.19872 3.47759 9.48483 2.5 12 2.5C17.2467 2.5 21.5 6.75329 21.5 12C21.5 17.2467 17.2467 21.5 12 21.5C7.1307 21.5 3.11828 17.8375 2.565 13.1164C2.50071 12.5679 2.89327 12.0711 3.4418 12.0068C3.99033 11.9425 4.48712 12.3351 4.5514 12.8836C4.98798 16.6089 8.15708 19.5 12 19.5C16.1421 19.5 19.5 16.1421 19.5 12C19.5 7.85786 16.1421 4.5 12 4.5C9.7796 4.5 7.7836 5.46469 6.40954 7H9C9.55228 7 10 7.44772 10 8C10 8.55228 9.55228 9 9 9H4.5C3.96064 9 3.52101 8.57299 3.50073 8.03859C3.49983 8.01771 3.49958 7.99677 3.5 7.9758V3.5C3.5 2.94772 3.94771 2.5 4.5 2.5Z" fill="currentColor"></path></svg></div></button></div></div></div></div>`

**Comment by adamlui** [comment]
嘿 @visayafan 这是否意味着我的扩展与该问题无关？

**Comment by adamlui** [comment]
Closing because ChatGPT Widescreen does not deal with message limits but display text expansion only
