### ISSUE TITLE
Feature request: Have the text input expand larger to fit large input

### ISSUE THREAD

**Issue by nhan000** [adamlui/chatgpt-widescreen#4]
When I put in a very large chunk of text and I want to edit it I need to scroll up and down quite a lot. Was wondering if there's a way to expand the input box larger (for me it can take up the whole screen, I just need to press `Enter` to submit it anyway). Don't know if you support this feature but I thought I'd just file a request for it. Thanks a lot!

![image](https://user-images.githubusercontent.com/85216095/232171378-17521b9b-703e-49f6-858b-947cc7b153b8.png)

**Comment by adamlui** [comment]
@nhan0000 that is an interesting idea and I will think about solutions!

**Comment by adamlui** [comment]
@nhan000 the chat input box is now very tall (in the userscript) do you like it?

**Comment by nhan000** [comment]
@adamlui I just uninstalled and reinstalled from this site https://greasyfork.org/en/scripts/461473-chatgpt-widescreen-mode and I don't think it's updated yet?

**Comment by adamlui** [comment]
@nhan000 that was very strange I had to manually click update in Admin dashboard to get the new script to sync (but now it's there)

**Comment by nhan000** [comment]
Besides you having to manually sync the script, there's also something wrong with updating the userscript on the user's end. It shows that there's an update a few minutes ago but when I clicked update all it did was to reinstall the old script. I had to refresh/uninstall about 5 times and I can update to the new version now. That is with Edge Stable. However, I still can't update the script on Firefox:

![image](https://user-images.githubusercontent.com/85216095/232182832-e60a2cd5-509d-4530-ba93-31f81337e6dd.png)

![image](https://user-images.githubusercontent.com/85216095/232182853-3fbeb83b-c1ce-4d2f-9f39-adfeb92d44df.png)

Regarding the input box, that's what I wanted. Thanks a lot! 

Though I just realized that it covered up some of the text above. Idk if other users would like it or not, so it's better to have a toggle (just like with notification and fuller window)? I don't know think it's is possible but it's best if the text box could expand downward instead of upward?

**Comment by nhan000** [comment]
@adamlui it just updated automatically on Firefox for me. All good now.

**Comment by adamlui** [comment]
> there's also something wrong with updating the userscript on the user's end

I actually raised this as a bug to Greasyfork owner and he said it's cuz he uses multiple servers so caching takes some time to clear

> Regarding the input box, that's what I wanted. Thanks a lot!

You're welcome!! If you want to help me out, could you consider giving this repo a ⭐? (It raises it in GitHub search results so more users can install)

> Though I just realized that it covered up some of the text above. Idk if other users would like it or not, so it's better to have a toggle 

I was originally gonna do that but it's going to be hard because I have to add logic to only show if input is tall (to not clash with other toggles) but I will work on that in the future

> but it's best if the text box could expand downward instead of upward

But the text box starts on the bottom edge of window so there's nowhere to go downward, unless you mean it hovers above the window and goes below bottom edge of window? (in which case it could be problem if window is maximized)

Also what plugin are you using for your beautiful dark mode on GF? 👀

**Comment by nhan000** [comment]
Will star your repo + leave a review on GF. Thanks a lot again!

I'm using Dark Reader for the dark mode on GF. I also think it's just needed some time to update properly after you push the changes.

And yep I also think having the text box to expand downward would not be straightforward (I don't know coding ha ha but I have a feeling it won't be as easy).

**Comment by adamlui** [comment]
> Will star your repo + leave a review on GF

Thank you for the star!!! Actually for review can you do it to the Chrome extension instead? @ https://chrome.google.com/webstore/detail/chatgpt-widescreen-mode/jgnjpnmofkalfliddjelaciggjgnphgm

You can install it in Edge or Chrome, then you will be allowed to review it on that page (but ironically it doesn't work yet until Google approves my updated code that fixes a change OpenAI made to URL from `https://chat.openai.com/chat` to `https://chat.openai.com/c`)
