### ISSUE TITLE
Broken with newest ChatGPT

### ISSUE THREAD

**Issue by asgeirtj** [adamlui/chatgpt-widescreen#50]
Doesn't seem to be working right now. Also is it possible to add feature to click enter key when chatgpt finishes it's response?

**Comment by asgeirtj** [comment]
I can now that this is happening because of the memory feature being rolled out in US and nearby regions

**Comment by adamlui** [comment]
hey @asgeirtj I don't have the new UI yet so don't know how to fix until it occurs :( also can you elaborate on this feature in https://github.com/adamlui/chatgpt-widescreen/discussions/new?category=ideas

**Comment by asgeirtj** [comment]
just vpn usa and you will get it :)

**Comment by adamlui** [comment]
I am american

**Comment by asgeirtj** [comment]
Seems that is also is not working with the Arc Browser, new UI or not.

**Comment by uniquMonte** [comment]
These days, it really can't be used.

**Comment by asgeirtj** [comment]
fyi one extension which still works is wide gpt if it can help you debug some.

**Comment by OhneNot** [comment]
@adamlui 
Please add the new URL to the chrome manifest
chrome/extension/manifest.json; Line 23
`"matches": ["https://chatgpt.com/", "https://chat.openai.com/*", "https://poe.com/*"],`

**Comment by adamlui** [comment]
hey@uniquMonte @asgeirtj @OhneNot I updated to work w/ new redirect, I will tag you guys when Google approves the update

**Comment by adamlui** [comment]
@uniquMonte @asgeirtj @OhneNot google approved the update https://chrome.chatgptwidescreen.com

**Comment by adamlui** [comment]
@asgeirtj can you confirmed it worked? then I will work on your new ideas possibly

**Comment by asgeirtj** [comment]
works now :) all extensions borked because of new url lol.

Kveðja / Regards, Ásgeir
