### ISSUE TITLE
Loss focus on input when new tab opened

### ISSUE THREAD

**Issue by auxten** [adamlui/chatgpt-widescreen#61]
Loss focus on input when new tab opened, this will make some auto procedure not work.
Please keep input cursor in the default input box!

**Comment by adamlui** [comment]
hey @auxten I just tested by disabling all extensions and userscript managers, my ChatGPT also loses focus by default behavior. Can you confirm this is true for you too?

**Comment by auxten** [comment]
It seems cursor will stay in input box while opening chatgpt.com without login(or Incognito mode)

**Comment by auxten** [comment]
Although it's not default behavior, do you think that will be better?

**Comment by adamlui** [comment]
I do think it will be better, but I am currently working on adding a Font Size slider for GoogleGPT/DuckDuckGPT/BraveGPT, so I can add this "Auto-Focus chatbar" option to ChatGPT Widescreen tomorrow, what do you think?

**Comment by adamlui** [comment]
hey because of your generous sponsorship I added it right away @auxten (userscript is live, Chrome extension will update in store probably by Sunday night)
