### ISSUE TITLE
Buttons in chat prompt acting weird

### ISSUE THREAD

**Issue by lars-vogel** [adamlui/chatgpt-widescreen#77]
![image](https://github.com/user-attachments/assets/c64f6c96-96d5-47d7-af2f-ffab87e7c881)

Probably a css issue?

**Comment by JakeYim** [comment]
Same issue in chrome.

**Comment by adamlui** [comment]
Thanks for re porting i'ma check it out now

**Comment by adamlui** [comment]
I can't replicate,

@lars-vogel are you using userscript or extension, if userscript which manager, also which browser?
@Anzar-M @JakeYim are you using userscript or extension, if userscript which manager?

**Comment by adamlui** [comment]
@Anzar-M I fixed the footer issue (OpenAI updated it so Hidden Footer styles stopped fully hiding the text), can you click your userscript manager's browser toolbar icon > scroll to ChatGPT Widescreen > About ChatGPT Widescreen > Check for updates > Update and confirm it's fixed?

**Comment by Anzar-M** [comment]
> I can't replicate,
> 
> @lars-vogel are you using userscript or extension, if userscript which manager, also which browser? @Anzar-M @JakeYim are you using userscript or extension, if userscript which manager?
> 
> Also any of you Plus users
**Userscript with tampermonkey. version=5.1.1**






> @Anzar-M I fixed the footer issue (OpenAI updated it so Hidden Footer styles stopped fully hiding the text), can you click your userscript manager's browser toolbar icon > scroll to ChatGPT Widescreen > About ChatGPT Widescreen > Check for updates > Update and confirm it's fixed?

Yes the footer issue in firefox is fixed.

**Comment by Anzar-M** [comment]
@adamlui 
So apparently **deleteing cookies and site data** fixed the issue.

**Comment by Sorena-29** [comment]
I also have the same issue. I am using Edge.
![Screenshot 2024-09-11 214401](https://github.com/user-attachments/assets/7c83d270-2bdc-446f-98c4-be0d404c2e25)

**Comment by Enissay** [comment]
Same issue here under ubuntu 22.04
![image](https://github.com/user-attachments/assets/48374819-d54c-448d-9b03-e0daf34d3795)
![image](https://github.com/user-attachments/assets/e30a9e16-a476-4c9f-be4b-7ca4eb1d14d5)

**Comment by adamlui** [comment]
Hey @lars-vogel @Anzar-M @JakeYim @Sorena-29 @Enissay thank you for reporting the issue, OpenAI finally updated my UI today so I was able to fix the bug, if you are using the userscript, to update click userscript manager icon in browser toolbar > scroll to ChatGPT Widescreen > Check for updates > Update, if you are using Chrome extension it will auto-update sometime tonight or tomorrow after Chrome review

**Comment by Sorena-29** [comment]
Works now finally.

**Comment by adamlui** [comment]
> Works now finally.

Edge team approved submitted update over weekend, Chrome team still has not (2024.9.13) so is still broken on Chrome
