### ISSUE TITLE
Do you have any plans to support perplexity?

### ISSUE THREAD

**Issue by comonetso** [adamlui/chatgpt-widescreen#78]
perplexity has been trending lately, 
I'm using perplexity a lot, and I'm trying to figure out how to use

chatGPT widescreen is being used too well.

Do you have any plans to support perplexity as well?

Thank you for developing such a great plugin.

**Comment by adamlui** [comment]
Thank you for the praise, I will investigate and add perplexity support probably when I have some time tomorrow

**Comment by comonetso** [comment]
Thank you so much for your interest and review.
I'm glad you've developed such a good plugin and I feel very comfortable using it.
I'm a developer myself, and I know how annoying and frustrating it can be. Parsing and analyzing the html and processing it accordingly is a real pain, not a challenge, but a real annoyance, so thank you again for being willing to do it for us.        

Also, thank you for being so quick to respond to each and every UI bug.

**Comment by adamlui** [comment]
@comonetso it's updated to support it now as of 2024.9.17

**Comment by comonetso** [comment]
Confirmed that it worked.
I have so much respect for you.
Thank you so much for your work.

Everything is going great, but can you please widen the chat box a little bit or bring it to the center? 

It's really hard on my eyes whenever I write, and it's aligned to the left.

I'm very happy with the way it is now.

Thank you.

**Comment by adamlui** [comment]
@comonetso the chatbar was trickier to manipulate on perplexity.ai is why I didn't hack it yet, but to confirm, is it ideal that when toggling widescreen on, chatbar stays unchanged, and if Wider Chatbox is on, it simply expands full-width

**Comment by adamlui** [comment]
@comonetso I finally made it auto-expand full-width and it will be in v2025.3.1+
