### ISSUE TITLE
"Full Window" was stuck on after updating

### ISSUE THREAD

**Issue by nh-pixel** [adamlui/chatgpt-widescreen#81]
Just updated to the newest version. The side panel was blocked/couldn't be shown whenever the extension is enabled, and toggling "Full Window" did nothing (it still sent the notification for on/off). 

Side panel buttons re-appeared after a few refreshes then were gone again. Disabling "Full Window" did nothing until I refreshed a dozen or so time and kept turning buttons on and off. This seemed to clear the error but it comes back after more refreshes. Trying to enable/disable different settings sometimes have an effect but other times fail. 

Just when I think I got it right the entire chat breaks on me. 
![chatgpt widescreen errors Screenshot 2024-09-15 121910](https://github.com/user-attachments/assets/8181416d-8513-4ada-a77b-bbc6abb9e211)

**Comment by adamlui** [comment]
Hey @nh-pixel all the issues went away with the latest update I submitted on Friday but Google still didn't approve it yet because the Chrome review team chills on the weekends sometimes (I think they are volunteer) but tonight around midnight is when it usually approves, the version is 2024.9.13

**Comment by adamlui** [comment]
@nh-pixel Chrome finally approved it, can you goto chrome://extensions > Update, and tell me if there are issues?

**Comment by nh-pixel** [comment]
Looking good! That seems to have fixed all the issues. Thanks you so much.

Cheers!😎🍻
