### ISSUE TITLE
宽屏模式的设置无法保存，切换到另外一个页面又恢复了默认的模式。

### ISSUE THREAD

**Issue by bushnerd** [adamlui/chatgpt-widescreen#84]

**Comment by adamlui** [comment]
@bushnerd Google 刚刚批准了最近的更新 v2024.9.25，您能否确认您正在使用此版本（或者您正在使用用户脚本？）

**Comment by bushnerd** [comment]
感谢回复，刚才更新了新版本，已经OK了。
后面能再增加一些new bing的宽屏模式吗？

**Comment by adamlui** [comment]
@bushnerd 好的，我会将其添加到任务列表中
