### ISSUE TITLE
Toggle function in chatGPT 4o Canvas

### ISSUE THREAD

**Issue by comonetso** [adamlui/chatgpt-widescreen#89]
I apologize for shamelessly asking you to do this

This time, chatGPT 4o Canvas was released,
but when you enter Canvas mode, if WideScreen extension is activated, the chat area becomes too narrow.

If you could add a function to temporarily turn off the wide screen function when Canvas is opened,
and then turn on the wide screen function when Canvas is closed, I would be very grateful.

It's too much of a hassle to turn it off and on every time..

Thank you.

**Comment by adamlui** [comment]
What's Canvas?

**Comment by comonetso** [comment]
![image](https://github.com/user-attachments/assets/6ea50345-7861-4067-bb48-14e3d664235b)

I'm referring to the canvas feature that was recently released in beta in open Ai.
chatGPT 4o Canvas feature.

**Comment by comonetso** [comment]
![image](https://github.com/user-attachments/assets/96028bf0-75dd-4889-aa7c-f1617c6c3850)

When the canvas opens as shown, you don't need the widescreen feature. 
Nevertheless, the related icon is in the chat window, which is too narrow to write on.
So we want to disable it when the canvas is open.

**Comment by adamlui** [comment]
I see, are you a Premium member? Because I don't have this feature so don't know how to detect it

**Comment by comonetso** [comment]
Yes, I'm a premium user.
I understand that chatGPT 4o Canvas will also be open to free users soon. 

Thank you for your interest.

**Comment by adamlui** [comment]
@comonetso if you want me to fix faster you could buy me Premium or I could login to your acct, otherwise we shall wait for the public release

**Comment by adamlui** [comment]
@comonetso I unwillingly bought Premium because it was really bugging me but the buttons hide now when Canvas is open as of 2024.10.11 (will approve and auto-update probably Sunday)
